# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

schedules:
- cron: "0 0 * * 3"
  displayName: Wednesday midnight build
  branches:
    include:
    - master
  always: true

trigger:
- master
- develop
- feature/*
- bugfix/*

pool:
  vmImage: 'windows-latest'

#variables:
#- group: QueoTransfer

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g dotnet-format --ignore-failed-sources'

#- task: NuGetAuthenticate@0
#  inputs:
#    nuGetServiceConnections: 'queo nuget commons'

- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
#    arguments: '--QueoTransferUrl="$(QueoTransferUrl)" --QueoTransferPort="$(QueoTransferPort)" --QueoTransferUser="$(QueoTransferUser)" --QueoTransferPwd="$(QueoTransferPwd)"'
